version: '3.7'

services:
    app:
        build: ./
        command: streamlit run streamlit_start.py --server.port=8501 --server.address=0.0.0.0
        volumes:
            - ./:/usr/src/app
        ports:
            - 8501:8501
        image: yourstreamlitapp:latest